version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - resume1/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - resume1/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn resume1.wsgi:application --bind 0.0.0.0:8000


volumes:
  postgresql-data:
  static-data:


