# Generated by Django 4.1.7 on 2023-08-21 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagesettings_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesettings',
            options={'ordering': ('name',), 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
        migrations.AddField(
            model_name='imagesettings',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='imagesettings',
            name='updated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='updated date'),
            preserve_default=False,
        ),
    ]
