# Generated by Django 4.1.7 on 2023-08-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
