# Generated by Django 4.1.7 on 2023-08-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
