# Generated by Django 4.1.7 on 2023-08-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
