# Generated by Django 4.1.7 on 2024-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_videosettings_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosettings',
            options={'ordering': ('order',), 'verbose_name': 'Video Setting', 'verbose_name_plural': 'Video Settings'},
        ),
        migrations.AlterField(
            model_name='videosettings',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This is a variable of setting.', max_length=254, verbose_name='Name'),
        ),
    ]
